require: rubocop-rspec

AllCops:
  Exclude:
    - db/**/*
    - vendor/**/*
    - config/environments/*

Style/Documentation:
  Enabled: false

Metrics/LineLength:
  Max: 120

Metrics/BlockLength:
  Exclude:
    - spec/**/*
    - config/routes.rb

Layout/IndentationConsistency:
  EnforcedStyle: indented_internal_methods

Style/ClassAndModuleChildren:
  Enabled: false

RSpec/DescribedClass:
  Enabled: false

Style/WordArray:
  EnforcedStyle: brackets

Style/SymbolArray:
  EnforcedStyle: brackets

Style/NumericLiterals:
  Enabled: false
    
RSpec/DescribeClass:
  Exclude:
    - spec/features/**/*

RSpec/NestedGroups:
  Max: 4
